
// comments can make code readable
// Welcome to 30DaysOfJavaScript

/*  comments can make code readable
 to reuse and informative
easy
*/

let a;
let b;
let c;
let d;

let a = 10;
let b = 5.5;
let c = "Hello";
let d = true;

/*
let name = "kalyani"
let last name = "sherkar"
let marital status = "married"
let country = "india"
let age = "29"
*/

// let name = "kalyani"
// let last name = "sherkar"
// let marital status ="married"
// let country = "india"
// let age = "29"

let myage =29
console.log(myage)

let yourage = 30
console.log(yourage)


